name: 'Weekday chart'

on:
# This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:
  
jobs:
  build chart:
    steps:
    - uses: brandmaier/weekdaychart@weekday
