name: 'Weekday chart'

on:
# This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: generate chart
      uses: brandmaier/weekdaychart@weekday
