name: 'Weekday chart'

on:
# This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: hi
    steps:
     - name: generate chart
       uses: brandmaier/weekdaychart@4238a99bdb56302d10425dc88e4cec0cb59d847e
