name: Test-R

on:
#  schedule: # 03:00 JST == 18:00 UTC
#    - cron: "0 18 * * *"
  workflow_dispatch:
  
permissions: write-all  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    name: generate graph
    steps:
     - name: Set up R
       uses: r-lib/actions/setup-r@v2
       with:
        r-version: 4.x
        use-public-rspm: true


     - name: Dependencies
       run: Rscript -e "install.packages('gh','dplyr','ggplot2')"
     - name: Checkout repository
       uses: actions/checkout@v2
       with:
          repository: brandmaier/brandmaier
          ref: main  # specify the branch 
        
     - name: Generate graph
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
       run: |
          Rscript graph.R

     - name: Commit & Push
       run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "updated weekday graph"
          git push
