name: Test-R

on:
#  schedule: # 03:00 JST == 18:00 UTC
#    - cron: "0 18 * * *"
  workflow_dispatch:
  
permissions: write-all  

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
     - name: Commit & Push
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
       run: |
          Rscript -e "print(Sys.getenv('USERNAME'))"
